
# File: .github/workflows/repo-sync.yml
name: 同步仓库
on:
  schedule:
    - cron: '0 0-16/2 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-i-chenzhe
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/DoveBoy/qx/"
          source_branch: "master"
          destination_branch: "i-chenzhe"
          github_token: ${{ secrets.PAT }}
