
# File: .github/workflows/repo-sync.yml
name: 同步仓库
on:
  schedule:
    - cron: '0 0-16/8 * * *'
  workflow_dispatch:
  watch:
    types: started
  push:
    branches: [ master ]
  repository_dispatch:
    types: sync
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} 
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync-moposmall
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/moposmall/Script.git"
          source_branch: "main"
          destination_branch: "moposmall"
          github_token: ${{ secrets.PAT }}

      - name: sync-passerby-b
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/passerby-b/JDDJ.git"
          source_branch: "main"
          destination_branch: "passerby-b"
          github_token: ${{ secrets.PAT }}

      - name: sync-yangtingxiao
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/yangtingxiao/QuantumultX.git"
          source_branch: "master"
          destination_branch: "yangtingxiao"
          github_token: ${{ secrets.PAT }}

      - name: sync-whyour
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/whyour/hundun.git"
          source_branch: "master"
          destination_branch: "whyour"
          github_token: ${{ secrets.PAT }}

      - name: sync-star
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/star261/jd.git"
          source_branch: "main"
          destination_branch: "star"
          github_token: ${{ secrets.PAT }}

      - name: sync-smiek
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/smiek2221/scripts.git"
          source_branch: "master"
          destination_branch: "smiek"
          github_token: ${{ secrets.PAT }}

      - name: sync-jiulan
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/jiulan/platypus.git"
          source_branch: "main"
          destination_branch: "jiulan"
          github_token: ${{ secrets.PAT }}

